# -*- coding: utf-8 -*-
"""mencari_bilangan.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qQ_jFlmuBhnkXU4bxsc22LvnsqaYAh98
"""

bil_input = int(input('Input= '))

for i in range(bil_input,0,-1):
  if (i%2 ==1):
    print(i, end=' ')