# -*- coding: utf-8 -*-
"""Mencari_huruf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yxujw1u1YmONGT7RZ8wafNcFqQS60_Xs
"""

Teks = str(input('Input = '))
Huruf_Vokal = ' '

for i in Teks :
  if i in 'aiueo' :
    Huruf_Vokal = Huruf_Vokal + i

print('Output = ', Huruf_Vokal)